CREATE DATABASE IF NOT EXISTS `DEVOPS`
USE `DEVOPS`;

CREATE TABLE IF NOT EXISTS `ESTADO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT (NOW()) ON UPDATE CURRENT_TIMESTAMP,
  `ESTADO` INT DEFAULT '0',
  `NOTAS` VARCHAR(150) COLLATE UTF8MB3_SPANISH_CI DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8MB3 COLLATE=UTF8MB3_SPANISH_CI;

INSERT INTO `ESTADO` (
  `ID`,
  `UPDATED`,
  `ESTADO`,
  `NOTAS`
) VALUES (
  1,
  '2024-01-17 17:04:55',
  0,
  'MANTENIMIENTO'
);

CREATE TABLE IF NOT EXISTS `OPCIONES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT (NOW()) ON UPDATE CURRENT_TIMESTAMP,
  `OPCION` VARCHAR(20) COLLATE UTF8MB3_SPANISH_CI NOT NULL,
  `TEXTO` VARCHAR(255) COLLATE UTF8MB3_SPANISH_CI NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB3 COLLATE=UTF8MB3_SPANISH_CI;

INSERT INTO `OPCIONES` (
  `ID`,
  `UPDATED`,
  `OPCION`,
  `TEXTO`
) VALUES (
  1,
  '2024-01-17 17:05:15',
  'opcion1',
  'Texto para opcion1'
),
(
  2,
  '2024-01-17 17:05:25',
  'opcion2',
  'Texto para opcion2'
),
(
  3,
  '2024-01-17 17:05:34',
  'opcion3',
  'Texto para opcion3'
),
(
  4,
  '2024-01-17 17:05:41',
  'opcion4',
  'Texto para opcion4'
);

CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UPDATED` TIMESTAMP NOT NULL DEFAULT (NOW()) ON UPDATE CURRENT_TIMESTAMP,
  `FIRST_NAME` VARCHAR(150) COLLATE UTF8MB3_SPANISH_CI DEFAULT NULL,
  `CHATID` VARCHAR(20) COLLATE UTF8MB3_SPANISH_CI NOT NULL,
  `USERNAME` VARCHAR(150) COLLATE UTF8MB3_SPANISH_CI DEFAULT NULL,
  `AUTORIZADO` INT DEFAULT '0',
  `PENDIENTE` INT DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3 COLLATE=UTF8MB3_SPANISH_CI;